Labs_Sem5/DataBase/Lab3/Lab3/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('crud.urls', namespace='crud')),
]

Labs_Sem5/DataBase/Lab3/crud/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.orders, name="home_page"),
    url(r'^producers_page', views.producers_page, name="producers_page"),
    url(r'^products', views.products_page , name='products_page'),
    url(r'^clients', views.clients_page , name='clients_page'),
    url(r'^make_order', views.make_order, name='make_order'),
    url(r'^edit_order', views.edit_order, name='edit_order'),
    url(r'^delete_order', views.delete_order, name='delete_order'),
    url(r'^delete_product', views.delete_product, name='delete_product'),
]

Labs_Sem5/DataBase/Lab3/crud/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Labs_Sem5/DataBase/Lab3/crud/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .dbmanager import Database
from .cashemanager import Cache
from datetime import datetime
import json

database = Database()
# database.fill_products()
cache = Cache()


def orders(request):
    # page_number = int(page_number)
    orders_ = [order for order in database.db.Order.find().limit(50)]
    clients = [order for order in database.db.Client.find()]
    products = [order for order in database.db.Product.find().limit(50)]
    if request.method == "POST":
        result_of_orders = database.sum_of_orders()
        result_of_buying = database.count_by_date()
        result_of_products = database.analize_orders()
        return render(request, 'crud/home.html', {'response': {'orders': orders_, 'clients': clients,
                                                                'products': products, 'results_of_orders': result_of_orders.find(),
                                                                'results_of_buying': result_of_buying.find(),
                                                                'results_of_products': result_of_products}})
    return render(request, 'crud/home.html', {'response': {'orders': orders_, 'clients': clients,
                                                            'products': products}})


def producers_page(request):
    return render(request, 'crud/index.html',  {'response': {'producers': database.db.Producer.find()}})


def clients_page(request):
    return render(request, 'crud/clients.html',  {'response': {'clients': database.db.Client.find()}})


def products_page(request):
    search = False
    if request.method == 'POST':
        product_title = request.POST['product_name'].lower()

        # words = set(product_title.split(' '))
        t0 = datetime.now()
        products = cache.search('products', product_title)
        dt1 = datetime.now() - t0

        if not products:
            t0 = datetime.now()
            products = database.search_products(product_title)
            dt2 = datetime.now() - t0
            if products:
                cache.cache_data('products', product_title, products)
                print ('Loaded from database!')
                print ("Database search: {}".format(dt2.total_seconds()))
        else:
            print ('Loaded from cache!')
            print ("Cache search: {}".format(dt1.total_seconds()))
        search = True
    else:
        products = [order for order in database.db.Product.find().limit(50)]
    return render(request, 'crud/products.html',  {'response': {'products': products,'flag': search}})


def make_order(request):
    if request.method == "POST":
        if request.POST["client_id"] != "" and request.POST["product_id"] != "":
            database.insert_order(request.POST)
        return HttpResponseRedirect('/')


def edit_order(request):
    if request.method == "POST":
        if request.POST["order_id"] != "" and request.POST["client_id"] != "" and request.POST["product_id"] != "":
            database.edit_order(request.POST)
        return HttpResponseRedirect('/')


def delete_order(request):
    if request.method == "POST":
        if request.POST["order_to_delete"] != "":
            database.delete_order(request.POST["order_to_delete"])
        return HttpResponseRedirect('/')


def delete_product(request):
    if request.method == "POST":
        if request.POST["product_to_delete"]:
            product_id = request.POST['product_to_delete']
            product = database.delete_product(product_id)
            cache.clear_cache('products', product)
        return HttpResponseRedirect('/products')

Labs_Sem5/DataBase/Lab3/crud/templates/crud/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'crud/bootstrap-3.3.6-dist/bootstrap-3.3.6-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>

    <title>Lab3</title>
</head>
<body background="">
{% include 'crud/header.html' %}
<div class="container-fluid ">
    <div class="jumbotron" style="height: auto">
        {% block content %}
        {% endblock %}
    </div>
</div>



</body>
</html>

Labs_Sem5/DataBase/Lab3/crud/templates/crud/clients.html
{% extends 'crud/base.html' %}
{% block content %}
<div class="row" >
  <div >
      <table class="table table-hover table-bordered table-responsive">
        <caption>
            <h3>Clients</h3>
        </caption>
        <thead>
            <!--<th>#</th>-->
            <th>Name</th>
            <th>Age</th>
        </thead>
        <tbody>
            {%  for client in response.clients %}
                <tr>
                    <td> {{ client.name}} </td>
                    <td> {{  client.age }} </td>
                    <!--<td> {{ client.2 }} </td>-->
                </tr>
            {% endfor %}
        </tbody>
      </table>
  </div>
</div>
{% endblock %}

Labs_Sem5/DataBase/Lab3/crud/templates/crud/header.html
<div style="background-color: yellowgreen">
  <nav class="navbar">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url "crud:home_page" %}">Orders</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li id="li1"><a href="{% url "crud:producers_page" %}">Manufacturer</a></li>
            <li id="li2"><a href="{% url "crud:products_page" %}">Products</a></li>
            <li id="li3"><a href="{% url "crud:clients_page" %}">Clients</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </nav>
</div> <!-- /container -->

Labs_Sem5/DataBase/Lab3/crud/templates/crud/home.html
{% extends 'crud/base.html' %}
{% load filters %}
{% block content %}

<div>
    <div class="row">
    <div class="col-md-8" style="border: 4px double black;">
        <h2>Make order</h2>
        <form action="make_order" method="POST" class="form-inline" style="">{% csrf_token %}
            <div class="col-md-2" >
              <label for="client_id" style="font-size: 18px; margin-top: 4px">Name:</label><br>
              <label style="font-size: 18px; margin-top: 6px">Product</label><br>
              <!--<label for="countid" style="font-size: 18px; margin-top: 3px" id="count_label">Count:</label><br>-->
            </div>
            <div class="col-md-6">
                <select id="client_id" name="client_id" style="width: 200px;height: 30px; border-radius: 5px">
                    {%  for client in response.clients %}
                        <option value="{{ client|private:'_id' }}" >{{client.name}}</option>
                    {% endfor %}
                </select>
                <div class="products">
                    <select class="product_item" name="product_id" style="margin-top:2%;width: 200px;height: 30px; border-radius: 5px">
                        {%  for product in response.products %}
                            <option value="{{ product|private:'_id' }}" >{{product.title}}</option>
                        {% endfor %}
                    </select>
                </div>
                <!--<input type="number" class="form-control" name="count" id="countid" style="margin-top:2%;">-->
            </div>
            <div class="col-md-1" style="margin-top: 3.5%;">
                <h3 style="cursor: pointer" id="add_product">+</h3>
            </div>
            <div class="col-md-1" style="margin-top: 3.5%;">
                <h3 style="cursor: pointer" id="remove_product">-</h3>
            </div>
            <div class="col-md-10" style="margin-top: 10px">
                <button type="submit" class="btn btn-default">Create order</button>
            </div>
        </form>
    </div>

    <div class="col-md-12"></div>

    <div class="col-md-8" style="border: 4px double black;">
        <h2>Edit order</h2>
        <form action="edit_order" method="POST" class="form-inline" style="height: auto;">{% csrf_token %}
            <div class="col-md-4" >
              <label for="order_id" style="font-size: 18px;">Number:</label><br>
              <label style="font-size: 18px; margin-top: 6%;">Name:</label><br>
              <label style="font-size: 18px; margin-top: 6%;">Product</label><br>
              <!--<label for="newcointid" style="font-size: 18px; margin-top: 6%;">Count:</label><br>-->
          </div>
          <div class="col-md-6">
              <select id="order_id" name="order_id" style="width: 200px;height: 30px; border-radius: 5px">
                  {%  for order in response.orders %}
                  <option value="{{ order|private:'_id' }}" >{{forloop.counter}}</option>
                  {% endfor %}
              </select>
              <select name="client_id" style="margin-top: 2%;width: 200px;height: 30px; border-radius: 5px">
                  {%  for client in response.clients %}
                    <option value="{{ client|private:'_id' }}" >{{client.name}}</option>
                  {% endfor %}
              </select>
              <div class="products_to_edit">
                  <select class="product_item_to_edit" name="product_id" style="margin-top: 2%;width: 200px;height: 30px; border-radius: 5px">
                    {%  for product in response.products %}
                        <option value="{{ product|private:'_id' }}" >{{product.title}}</option>
                    {% endfor %}
                  </select>
              </div>

              <!--<input type="number" class="form-control" name="count" id="newcointid" style="margin-top: 2%">-->
          </div>
            <div class="col-md-1" style="margin-top: 10%;">
                <h3 style="cursor: pointer" id="add_product_to_edit">+</h3>
            </div>
            <div class="col-md-1" style="margin-top: 10%;">
                <h3 style="cursor: pointer" id="remove_product_to_edit">-</h3>
            </div>
            <div class="col-md-10" style="margin-top: 10px">
                <button type="submit" class="btn btn-default">Save to database</button>
            </div>
        </form>
    </div>
    </div>
    <div class="col-md-12">
        <div class="col-md-6">
            <form action="/" method="POST" class="form-inline" style="height: auto;">{% csrf_token %}
                <button type="submit" class="btn btn-default">Count up all orders and analize products</button>
            </form>
             {% if response.results_of_orders%}
                <h2>Purchase amount : </h2>
                {% for result in response.results_of_orders%}
                    <h3>Client: {{result|private:"_id"}} - {{result.value}}$</h3>
                {% endfor %}
                <h2>Orders statistics: </h2>
                {% for product in response.results_of_buying%}
                    <h3>Date: {{product|private:"_id"}} - {{product.value}} orders</h3>
                {% endfor %}
                <h2>Products statistics: </h2>
                {% for product in response.results_of_products%}
                    <h3>Product: {{product|private:"_id"}} - {{product.count}} times</h3>
                {% endfor %}
            {% endif %}
        </div>
        <div class="col-md-6">

        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        var margin = 3;
        var count = 1;
        $('#remove_product').click(function () {
            if (count > 1){
                margin-=33;
                $('.product_item:last-child').remove();
                count--;
            }
        });

        $('#add_product').click(function () {
            count++;
            margin+=33;
            $('.products').append('<select class="product_item" name="product_id" style="margin-top:2%;width: 200px;height: 30px; border-radius: 5px">\
                    {%  for product in response.products %}\
                        <option value="{{ product|private:'_id' }}" >{{product.title}}</option>\
                    {% endfor %}\
                </select>');


        });

        var margin_to_edit = 3;
        var count_to_edit = 1;
        $('#remove_product_to_edit').click(function () {
            if (count_to_edit > 1){
                margin_to_edit-=33;
                $('.product_item_to_edit:last-child').remove();
                count_to_edit--;
            }
        });

        $('#add_product_to_edit').click(function () {
            count_to_edit++;
            margin_to_edit+=33;
            $('.products_to_edit').append('<select class="product_item_to_edit" name="product_id" style="margin-top:2%;width: 200px;height: 30px; border-radius: 5px">\
                    {%  for product in response.products %}\
                        <option value="{{ product|private:'_id' }}" >{{product.title}}</option>\
                    {% endfor %}\
                </select>');


        });

    });
</script>

<div class="row">
      <table class="table table-hover table-bordered table-responsive" style=" background-color: #f2f2f2">
        <caption>
            <h3>Orders</h3>
        </caption>
        <thead>
            <th>#</th>
            <th>Client</th>
            <th>Manufacturer</th>
            <th>Date</th>
            <th>Delete</th>
        </thead>
        <tbody>
            {%  for order in response.orders %}
                <tr>
                    <td> {{forloop.counter}} </td>
                    <td> {{ order.client.name }} </td>
                    <td>
                        {%  for product in order.product %}
                            {{ product.title }} <br>
                        {% endfor %}
                    </td>
                    <td> {{ order.date }} </td>
                    <td>
                        <form action="delete_order" method="POST">{% csrf_token %}
                            <button name="order_to_delete" value='{{ order|private:"_id"}}' type="submit" class="btn btn-default" style="">Delete order</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
      </table>

</div>


{% endblock %}

Labs_Sem5/DataBase/Lab3/crud/templates/crud/index.html
{% extends 'crud/base.html' %}
{% block content %}
<div class="row">
  <div class="col-lg-6">
      <table class="table table-hover table-bordered table-responsive">
        <caption>
            <h3>Manufacturer</h3>
        </caption>
        <thead>
            <!--<th>#</th>-->
            <th>Title</th>
            <th>Country</th>
        </thead>
        <tbody>
            {%  for producers in response.producers %}
                <tr>
                    <td>{{ producers.title }}</td>
                    <td>{{  producers.country }} </td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
  </div>
</div>


{% endblock %}

Labs_Sem5/DataBase/Lab3/crud/templates/crud/products.html
{% extends 'crud/base.html' %}
{% block content %}
{% load filters %}
<div class="row" >
  <div >
      <table class="table table-striped">
        <caption>
                <h1 class="text-center">Products</h1>
            <form action="products" method="post">{% csrf_token %}
                <div class="row">
                    <input class="" type="text" name="product_name" style="width: 200px; margin-left: 70%;">
                    <button class="btn btn-danger" style="margin-bottom: 0.5%; outline: none;">Search</button>
                </div>

            </form>
        </caption>
        <thead>
            <th>ID</th>
            <th>Title</th>
            <!--<th>Bestseller</th>-->
            <!--<th>Description</th>-->
            <th>Price</th>
            <th>Manufacturer</th>
            {% if not response.flag %}
                <th>Delete</th>
            {% endif %}
        </thead>
        <tbody>
            {%  for product in response.products %}
                <tr>
                    <td> {{ forloop.counter }}</td>
                    <td> {{ product.title }} </td>
                    <td> {{  product.price }} </td>
                    <td> {{ product.producer.title }} </td>
                    {% if not response.flag %}
                    <td>
                        <form action="delete_product" method="POST">{% csrf_token %}
                            <button name="product_to_delete" value="{{ product|private:'_id'}}" type="submit" class="btn btn-default">Delete product</button>
                        </form>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
      </table>
  </div>
  <!--<div class="col-md-12">-->
      <!--<div class="col-md-4">-->
          <!--<form action="show_bestsellers" method="POST">{% csrf_token %}-->
            <!--<button type="submit" class="btn btn-default">Show bestsellers</button>-->
          <!--</form>-->
      <!--</div>-->
      <!--<div class="col-md-4">-->
          <!--<form action="search_bool_mode" method="POST">{% csrf_token %}-->
            <!--<button type="submit" class="btn btn-default">Search by word</button>-->
            <!--<input type="text" class="form-control" name="title"  placeholder="Search"><br>-->
          <!--</form>-->
          <!--<form action="search_phrase" method="POST">{% csrf_token %}-->
            <!--<button type="submit" class="btn btn-default">Search by phrase</button>-->
            <!--<input type="text" class="form-control" name="title"  placeholder="Search"><br>-->
          <!--</form>-->
      <!--</div>-->
      <!--<div class="col-md-4">-->
          <!--<form action="filtred_products" method="POST">{% csrf_token %}-->
              <!--<div class="col-md-6">-->
                  <!--<button type="submit" class="btn btn-default">Search by range</button>-->
                  <!--<input type="number" class="form-control" name="from"  placeholder="From">-->
              <!--</div>-->
              <!--<div class="col-md-6">-->
                  <!--<input type="number" class="form-control" name="to" placeholder="To" style="margin-top: 33px">-->
              <!--</div>-->

          <!--</form>-->
      <!--</div>-->
  <!--</div>-->
</div>
<br>
<br>

{% endblock %}